APPLICATION = multithreading
BOARD=unwd-range-l1-r3
RIOTBASE ?= $(CURDIR)/../../RIOT
DEVELHELP ?= 1
FEATURES_REQUIRED += periph_gpio
FEATURES_REQUIRED += periph_timer
USEMODULE += periph_gpio_irq
USEMODULE += xtimer
QUIET ?= 1

include $(RIOTBASE)/Makefile.include

